enum {
	LOGMODE_NONE = 0,
	LOGMODE_STDIO = (1 << 0),
	LOGMODE_SYSLOG = (1 << 1) * 
#if definedEx(CONFIG_FEATURE_SYSLOG)
1
#endif
#if !definedEx(CONFIG_FEATURE_SYSLOG)
0
#endif
,
	LOGMODE_BOTH = LOGMODE_SYSLOG + LOGMODE_STDIO,
};

enum  {
  FILEUTILS_PRESERVE_STATUS = (1 << 0),
  FILEUTILS_DEREFERENCE = (1 << 1),
  FILEUTILS_RECUR = (1 << 2),
  FILEUTILS_FORCE = (1 << 3),
  FILEUTILS_INTERACTIVE = (1 << 4),
  FILEUTILS_MAKE_HARDLINK = (1 << 5),
  FILEUTILS_MAKE_SOFTLINK = (1 << 6),
  FILEUTILS_DEREF_SOFTLINK = (1 << 7),
  FILEUTILS_DEREFERENCE_L0 = (1 << 8),

  #if (definedEx(CONFIG_FEATURE_FIND_CONTEXT) || definedEx(CONFIG_SELINUX))
  FILEUTILS_PRESERVE_SECURITY_CONTEXT = (1 << 9),
  #endif

  #if (definedEx(CONFIG_FEATURE_FIND_CONTEXT) || definedEx(CONFIG_SELINUX))
  FILEUTILS_SET_SECURITY_CONTEXT = (1 << 10)
  #endif

} ;

void main() {}