
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// [date omitted]
//----------------------------------------------------

package expressionParser;

/** CUP generated interface containing symbol constants. */
public interface FeatureModelSym {
  /* terminals */
  public static final int AND = 5;
  public static final int CBRACKETS = 9;
  public static final int TRUE = 3;
  public static final int OBRACKETS = 8;
  public static final int EOF = 0;
  public static final int FALSE = 4;
  public static final int ONE_OF = 11;
  public static final int SOME_OF = 13;
  public static final int COMMA = 10;
  public static final int error = 1;
  public static final int IDENTIFIER = 2;
  public static final int NOT = 7;
  public static final int ONE_OF_OR_NONE = 14;
  public static final int NONE_OF = 12;
  public static final int OR = 6;
  public static final int DEFINED = 15;
}

